# Generated by Django 3.1.2 on 2021-01-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.FloatField(blank=True, default='-')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('release_date', models.DateField(blank=True, default='-')),
                ('lte_exists', models.BooleanField(blank=True, default='NULL', null=True)),
                ('slug', models.CharField(max_length=80)),
            ],
        ),
    ]
